// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI8gyzTWveIikJoX_-XsFtFtZZ4k3NGwU',
    appId: '1:385086121177:web:b11840a6060085034a0ac8',
    messagingSenderId: '385086121177',
    projectId: 'employee-leave-managemen-44d3a',
    authDomain: 'employee-leave-managemen-44d3a.firebaseapp.com',
    storageBucket: 'employee-leave-managemen-44d3a.appspot.com',
    measurementId: 'G-JNG40GNVME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfNVwWnSL-jiuOH8PFoevPSFJVFz-21Oo',
    appId: '1:385086121177:android:10a570c9a92c81c84a0ac8',
    messagingSenderId: '385086121177',
    projectId: 'employee-leave-managemen-44d3a',
    storageBucket: 'employee-leave-managemen-44d3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz-pT-KnXa6z5lzJUumi8HGY4UWGTFKs8',
    appId: '1:385086121177:ios:7ebadf5d10d25a974a0ac8',
    messagingSenderId: '385086121177',
    projectId: 'employee-leave-managemen-44d3a',
    storageBucket: 'employee-leave-managemen-44d3a.appspot.com',
    iosClientId: '385086121177-7k3fe7fkb4gbiu2vrip66nervvb2qp2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeeManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz-pT-KnXa6z5lzJUumi8HGY4UWGTFKs8',
    appId: '1:385086121177:ios:7ebadf5d10d25a974a0ac8',
    messagingSenderId: '385086121177',
    projectId: 'employee-leave-managemen-44d3a',
    storageBucket: 'employee-leave-managemen-44d3a.appspot.com',
    iosClientId: '385086121177-7k3fe7fkb4gbiu2vrip66nervvb2qp2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeeManagement',
  );
}
